include:
  - project: 'Northern.tech/Mender/mendertesting'
    file:
      - '.gitlab-ci-check-commits.yml'
      - '.gitlab-ci-github-status-updates.yml'

stages:
  - test

.test:static:
  stage: test
  image: ubuntu:24.04
  needs: []
  before_script:
    - apt-get update && apt-get install -y git clang-format pcregrep

test:static:license:
  extends: .test:static
  script:
    - ./.github/workflows/check_headers.sh

test:static:format:
  extends: .test:static
  script:
    - ./.github/workflows/check_include_guards.sh
    - ./.github/workflows/check_equivalence_tests.sh
    - ./.github/workflows/check_code_format.sh

test:smoke-build:posix:
  stage: test
  image: debian:12-slim
  needs: []
  before_script:
    - apt-get update && apt-get install -y git cmake libcurl4-openssl-dev
  script:
    - cmake -C cmake/CMake_posix_defaults.txt -B build tests/smoke
    - cmake --build build --parallel $(nproc --all)
    - ./build/mender-mcu-client.elf --help

test:smoke-build:weak:
  stage: test
  image: debian:12-slim
  needs: []
  before_script:
    - apt-get update && apt-get install -y git cmake libcurl4-openssl-dev
  script:
    - cmake -C cmake/CMake_weak_defaults.txt -B build tests/smoke
    - cmake --build build --parallel $(nproc --all)
    - ./build/mender-mcu-client.elf --help
